---
AWSTemplateFormatVersion: 2010-09-09
Description: SESEmailHandlerECRRepository

Resources:
  SESEmailHandlerECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: ses-email-handler
      Tags:
        - Key: "Name"
          Value: "ses-email-handler"

Outputs:
  Arn:
    Value: !GetAtt SESEmailHandlerECRRepository.Arn


# aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 483158796244.dkr.ecr.us-east-1.amazonaws.com
# aws cloudformation create-stack --stack-name IntSiteCallerUploadHandlerECRRepository --template-body file://repository.yml  --profile=<your_profile> --region=us-east-1 --capabilities CAPABILITY_NAMED_IAM;
